language: python
python: 
  - "3.8.2"
services:
  - postgresql

install:
  - pip install -r requirements.txt
before_script:
  - psql -c 'create database tradecycledb;' -U postgres
  - psql -c 'create extension if not exists unaccent;' -U postgres

script: 
  - ./manage.py migrate
  - ./manage.py test