# Generated by Django 3.1 on 2020-08-18 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('give', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('description', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='ads/photos')),
                ('city', models.CharField(max_length=50)),
                ('is_open', models.BooleanField(default=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
